#!/usr/bin/env python3

from itertools import repeat
import os
import sys

import pytest


base_dir = os.path.dirname(os.path.realpath(__file__))

register_endpoint_args = [arg
                          for register in sys.argv[1:]
                          for arg in ('--endpoint', register)]

args = [base_dir] + register_endpoint_args

pytest.main(args)
