#!/usr/bin/env python3

import argparse
from itertools import repeat
import os
import sys

import pytest


parser = argparse.ArgumentParser()
parser.add_argument("endpoint", nargs="+", help="URL(s) of register to test")
parser.add_argument("--no-https", help="suppress tests for HTTPS functionality", action="store_true")
args = parser.parse_args()

base_dir = os.path.dirname(os.path.realpath(__file__))


pytest_args = [base_dir, '-q']

if args.no_https:
    pytest_args += ['-m','not https']

for register in args.endpoint:
    print(register)
    pytest_args += ['--endpoint', register]

raise SystemExit(pytest.main(pytest_args))
