#!/usr/bin/env python3

import argparse
import os

import pytest

parser = argparse.ArgumentParser()
parser.add_argument("endpoint", help="URL of register to test")
parser.add_argument("--register", help="name of the register to run conformance tests for")
parser.add_argument("--no-https", help="suppress tests for HTTPS functionality", action="store_true")
parser.add_argument("--register-domain", help="domain of the register")

args = parser.parse_args()

base_dir = os.path.dirname(os.path.realpath(__file__))

pytest_args = [base_dir, '-q', '-s']

if args.no_https:
    pytest_args += ['-m', 'not https']

print(args.endpoint)
pytest_args += ['--endpoint', args.endpoint]
pytest_args += ['--register', args.register]
pytest_args += ['--register-domain', args.register_domain]

raise SystemExit(pytest.main(pytest_args))
